version: "3.1"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
  adminer:
    image: adminer
    ports:
      - 8080:8080
    restart: always
